DROP TABLE transactions;
DROP TABLE utilisateurs;
DROP TABLE casiers;

CREATE TABLE utilisateurs (
    adresseMail     varchar(32) NOT NULL,
    prenom           varchar(32) NOT NULL,
    nom              varchar(32) NOT NULL,
    hashPassword    varchar(256) NOT NULL,
    credit           int DEFAULT 0,
    PRIMARY KEY (adresseMail)
);

CREATE TABLE casiers (
    idCasier        int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    largeur          int DEFAULT 30,
    hauteur          int DEFAULT 30,
    estPlein        int DEFAULT 0,
    poids            int DEFAULT 0, 
    PRIMARY KEY (idCasier)
);

CREATE TABLE transactions (
    idTransaction    int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    dateTrans        date NOT NULL,
    typeTrans        char(11) NOT NULL,
    utilisateur      varchar(32) NOT NULL,
    idCasier         int,
    PRIMARY KEY(idTransaction),
    CONSTRAINT enum_type_trans
        CHECK (typeTrans='depot' 
            OR typeTrans='retrait' 
            OR typeTrans='connexion' 
            OR typeTrans='deconnexion'
            OR typeTrans='echange'),
    CONSTRAINT transactions_casier
        FOREIGN KEY (idCasier) REFERENCES casiers (idCasier),
    CONSTRAINT transactions_utilisateur
        FOREIGN KEY (utilisateur) REFERENCES utilisateurs (adresseMail)
);
