DROP TABLE transactions;
DROP TABLE utilisateurs;
DROP TABLE casiers;

CREATE TABLE utilisateurs (
    adresse_mail     varchar(32) NOT NULL,
    prenom           varchar(32) NOT NULL,
    nom              varchar(32) NOT NULL,
    hash_password    varchar(256) NOT NULL,
    credit           int DEFAULT 0,
    PRIMARY KEY (adresse_mail)
);

CREATE TABLE casiers (
    id_casier        int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    largeur          int DEFAULT 30,
    hauteur          int DEFAULT 30,
    est_plein        int DEFAULT 0,
    poids            int DEFAULT 0, 
    PRIMARY KEY (id_casier)
);

CREATE TABLE transactions (
    id_transaction    int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_trans        date NOT NULL,
    type_trans        char(11) NOT NULL,
    utilisateur      varchar(32) NOT NULL,
    id_casier         int,
    PRIMARY KEY(id_transaction),
    CONSTRAINT enum_type_trans
        CHECK (type_trans='depot' 
            OR type_trans='retrait' 
            OR type_trans='connexion' 
            OR type_trans='deconnexion'),
    CONSTRAINT transactions_casier
        FOREIGN KEY (id_casier) REFERENCES casiers (id_casier),
    CONSTRAINT transactions_utilisateur
        FOREIGN KEY (utilisateur) REFERENCES utilisateurs (adresse_mail)
);
