INSERT INTO MEIGNANM.UTILISATEURS (ADRESSEMAIL, PRENOM, NOM, HASHPASSWORD, CREDIT) 
	VALUES ('meignanm@ensimag.fr', 'Maxime', 'Meignan', 'DEAD', 2);
INSERT INTO MEIGNANM.UTILISATEURS (ADRESSEMAIL, PRENOM, NOM, HASHPASSWORD, CREDIT) 
	VALUES ('bombrunt@ensimag.fr', 'Thomas', 'Bombrun', 'BEEF', 3);
INSERT INTO MEIGNANM.UTILISATEURS (ADRESSEMAIL, PRENOM, NOM, HASHPASSWORD, CREDIT) 
	VALUES ('locteauh@ensimag.fr', 'Hugo', 'Locteau', 'CACA0', 5);
INSERT INTO MEIGNANM.UTILISATEURS (ADRESSEMAIL, PRENOM, NOM, HASHPASSWORD, CREDIT) 
	VALUES ('dobrescg@ensimag.fr', 'Gina', 'Dobrescu', 'CAFE', 4);
