INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (1, 10, 10, 0, 0);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (2, 10, 10, 0, 0);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (3, 10, 10, 0, 0);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (4, 10, 10, 0, 0);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (5, 10, 10, 0, 0);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (6, 10, 10, 0, 0);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (7, 10, 10, 0, 0);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (8, 10, 10, 1, 100);
INSERT INTO MEIGNANM.CASIERS (IDCASIER, LARGEUR, HAUTEUR, ESTPLEIN, POIDS) 
	VALUES (9, 10, 10, 1, 100);


